### ISSUE TITLE
Couldnt get working on VS22

### ISSUE THREAD

**Issue by R3uan3** [koszeggy/KGySoft.Drawing.Tools#7]
In this small test sample:
```c++
    ULONG_PTR gdiplusToken;
    GdiplusStartupInput gdiplusStartupInput;
    GdiplusStartup(&gdiplusToken, &gdiplusStartupInput, NULL);
    int width, height = 200;
    Bitmap bitmap(width, height, PixelFormat32bppARGB);
    Graphics graphics(&bitmap);

    SolidBrush brush(Color(255, 255, 0, 0));
    graphics.FillRectangle(&brush, 0, 0, width, height);

    CLSID pngClsid;
    GetEncoderClsid(L"image/png", &pngClsid);
    bitmap.Save(L"test.png", &pngClsid, NULL);
```

When i hover `bitmap` or `graphics` i'm not seeing the magnifier icon, neither in the debugger watch window.
![image](https://github.com/koszeggy/KGySoft.Drawing.Tools/assets/103058225/c25bf9df-cba1-45d4-a220-142f570cc45f)

Also, is it possible to preview HBITMAPs?

I'm using VS22 17.6.5
I have installed the extension from the market place.
I also checked `KGySoft.Drawing.ImagingTools.exe` at `Documents`
![image](https://github.com/koszeggy/KGySoft.Drawing.Tools/assets/103058225/c810e0ca-1254-4ca7-850e-74f0262578c4)

**Comment by koszeggy** [comment]
Thank you for your report.

The posted snippet and screenshot appears to be a C++ code. The visualizers support the .NET wrapper types of the GDI+ classes only, so the ones in the `System.Drawing` namespace, eg. [`System.Drawing.Graphics`](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.graphics) rather than the native [`Gdiplus::Graphics`](https://learn.microsoft.com/en-us/windows/win32/api/gdiplusgraphics/nl-gdiplusgraphics-graphics).

But actually in a [C++/CLI project](https://learn.microsoft.com/en-us/cpp/dotnet/dotnet-programming-with-cpp-cli-visual-cpp) (formerly: Managed C++) you can [use GDI+ types](https://learn.microsoft.com/en-us/cpp/dotnet/graphics-operations-cpp-cli) via their managed .NET wrappers. And then the visualizers become available also in a C++ project:

![KGy SOFT Debugger Visualizers in a C++/CLI project](https://github.com/koszeggy/KGySoft.Drawing.Tools/assets/27336165/241fc278-f8ef-4241-81f3-208698e5d9ed)

> Also, is it possible to preview HBITMAPs?

Not directly, but you can turn your `HBITMAP` to a `System.Drawing.Bitmap` instance by the [`Image.FromHbitmap`](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.image.fromhbitmap) method.

**Comment by R3uan3** [comment]
If i understood it correctly, it will only work on a CLR project?

I would like to also ask, do you have any extension to preview images in comments?

**Comment by koszeggy** [comment]
> If i understood it correctly, it will only work on a CLR project?

Yes. If the appropriate templates are not available, [this](https://learn.microsoft.com/en-us/cpp/dotnet/dotnet-programming-with-cpp-cli-visual-cpp) article explains how to add them for an already installed Visual Studio. In Visual Studio Installer you need to select the **C++/CLI Support for v143 build tools (latest)** component:

![image](https://github.com/koszeggy/KGySoft.Drawing.Tools/assets/27336165/7e14354c-5837-4dbf-9629-fe156e1ac704)

And then you can select a bunch of CLR project types for C++. For example, for the code in my first answer I just selected the **CLR Console App** template:

![image](https://github.com/koszeggy/KGySoft.Drawing.Tools/assets/27336165/abd5cd27-f685-4bc4-b1ce-951213862853)

📝 _Side note:_ If you want to use managed GDI+ in a Desktop application with Win32 windows, you might want to create a Windows Forms project. For C# it's a trivial choice, as there is already a built-in _Windows Forms App_ template for C# but for C++ it's a bit more complicated. [This video](https://youtu.be/TpLGRyUEFwY) explains how to add a form to an empty CLR project, or you can use some 3rd party templates like [this one](https://marketplace.visualstudio.com/items?itemName=RichardKaiser.cppclrwinf). And once you can use forms, using `Graphics` becomes natural, for example in the `OnPaint` methods of the controls as described in [this](https://learn.microsoft.com/en-us/cpp/dotnet/graphics-operations-cpp-cli) article.

> I would like to also ask, do you have any extension to preview images in comments?

I'm not sure if I get it correctly. In what format would you embed images into comments? Anyway, URLs to images are rendered as links so Ctrl+Click works for them. If you mean the XML comments documentation, then there are extensions that can render a preview of them (eg. GhostDoc). Or, for markdown files the [MarkdownEditor](https://github.com/MadsKristensen/MarkdownEditor2022) can render the documentation on-the-fly, along with images.

**Comment by R3uan3** [comment]
Thank you for the detailed answer! I'm not working with c#, I'm working with C++ and Qt, I'm using GDI+ mostly for image search, I'm not drawing anything, I have the haystack images converted to text/bits and compare them, being able to visualize the BITMAPS/HBITMAPS on memory would while debugging.

These images rendered on comments are from this [extension](https://marketplace.visualstudio.com/items?itemName=RisAdams.Illuminatedcomments).
I wonder if it could be possible to render multiple images on the same line, and also create a preview of them with their full size when hovered.

**Comment by koszeggy** [comment]
Ah ok, I get it now. My extension opens the visualizer in a dialog though, where you can save or even edit/replace the debugged image if it's a `Bitmap`, `Metafile` or `Icon`, and the debugged variable or property is not read-only.

**Comment by R3uan3** [comment]
Do you accept request for creating an extension like this?

**Comment by koszeggy** [comment]
No, thank you. I'm not aiming for parsing comments and as I see there is an already existing extension for that purpose.
